---
title: "data_import"
author: "Catherine"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import FAS csv files

Import my first csv.

```{r}
## Relative paths are portable, in that if you move your directory or share it with someone else, the relative path to files in the directory will stay the same and your code will work. 
litters_data = read_csv(file = "./data/FAS_litters.csv")
## The 'package::function' syntax lets you use a function from a package without loading the whole library.
litters_data = janitor::clean_names(litters_data)
names(litters_data)
## Learning Assessment
pups_data = read_csv(file = "./data/FAS_pups.csv")
```

## Look at data

Look at litters data.

```{r}
head(litters_data)
tail(litters_data)

skimr::skim(litters_data)
## View() are using in console when you are dealing with data and make sure everything is going well. But it will create error when knit it.
```

Look at pups data.

```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv", col_types = "diiiii")
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)
```

Skip the first 50 lines of data and not assume the first row are variable names.

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  skip = 10, col_names = FALSE)
head(litters_data)
```

## Read other data

Read excel data.

```{r}
mlb11_data = readxl::read_excel("./data/mlb11.xlsx", n_max = 20)
mbl_subset = readxl::read_excel("./data/mlb11.xlsx", range = "A1:E17")
head(mlb11_data, 5)
lotR_data = readxl::read_excel("./data/LotR_Words.xlsx")
```

Read sas data.

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
head(pulse_data, 5)
```




